#!/bin/bash
#
# Batch Processing Test Commands
#
# Quick reference for all batch processing tests and benchmarks
#

set -e

echo "================================================================================"
echo "BATCH PROCESSING TEST COMMANDS"
echo "================================================================================"
echo ""

# Color codes
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Base directory
BASE_DIR="/home/devuser/workspace/hackathon-tv5/semantic-recommender"

echo -e "${BLUE}1. VERIFY IMPLEMENTATION${NC}"
echo "   Check that all components are correctly implemented"
echo ""
echo "   python3 $BASE_DIR/scripts/tests/verify_batch_implementation.py"
echo ""
echo "   Expected: All 25 checks pass (100% success rate)"
echo ""
echo "================================================================================"
echo ""

echo -e "${BLUE}2. START SERVER${NC}"
echo "   Start Flask server with batch processing"
echo ""
echo "   python3 $BASE_DIR/scripts/server/query_interface.py"
echo ""
echo "   Server will start on http://0.0.0.0:5000"
echo ""
echo "================================================================================"
echo ""

echo -e "${BLUE}3. CHECK SERVER STATUS${NC}"
echo "   Verify server is running and batch processor is enabled"
echo ""
echo "   curl http://localhost:5000/api/status | jq"
echo ""
echo "   Or just batch processor status:"
echo "   curl http://localhost:5000/api/status | jq '.batch_processor'"
echo ""
echo "================================================================================"
echo ""

echo -e "${BLUE}4. TEST SINGLE QUERY${NC}"
echo "   Test single query without batching"
echo ""
echo "   curl -X POST http://localhost:5000/api/query \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"query\": \"action movies\", \"limit\": 5}'"
echo ""
echo "   Test single query WITH batching:"
echo "   curl -X POST http://localhost:5000/api/query \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"query\": \"action movies\", \"limit\": 5, \"use_batch\": true}'"
echo ""
echo "================================================================================"
echo ""

echo -e "${BLUE}5. TEST BATCH QUERY${NC}"
echo "   Test batch endpoint with multiple queries"
echo ""
echo "   curl -X POST http://localhost:5000/api/query/batch \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"queries\": [\"action\", \"comedy\", \"thriller\"], \"limit\": 5}'"
echo ""
echo "================================================================================"
echo ""

echo -e "${BLUE}6. RUN FUNCTIONAL TESTS${NC}"
echo "   Run all functional tests (5 scenarios)"
echo ""
echo "   python3 $BASE_DIR/scripts/tests/test_batch_processing.py"
echo ""
echo "   Tests:"
echo "   - Single query (baseline)"
echo "   - Sequential queries (100)"
echo "   - Batch endpoint (100)"
echo "   - Individual with batch flag (100)"
echo "   - Concurrent batch queries (10 workers × 10 queries)"
echo ""
echo "================================================================================"
echo ""

echo -e "${BLUE}7. RUN QPS BENCHMARK${NC}"
echo "   Measure QPS with different configurations"
echo ""
echo "   Standard benchmark (1000 queries):"
echo "   python3 $BASE_DIR/scripts/tests/benchmark_batch_qps.py"
echo ""
echo "   Custom configuration:"
echo "   python3 $BASE_DIR/scripts/tests/benchmark_batch_qps.py \\"
echo "     --requests 1000 --workers 20 --batch-size 32"
echo ""
echo "   High load test (10K queries):"
echo "   python3 $BASE_DIR/scripts/tests/benchmark_batch_qps.py \\"
echo "     --requests 10000 --workers 50"
echo ""
echo "   Stress test (100K queries):"
echo "   python3 $BASE_DIR/scripts/tests/benchmark_batch_qps.py \\"
echo "     --requests 100000 --workers 100"
echo ""
echo "   Expected: QPS >= 1000 with TensorRT"
echo ""
echo "================================================================================"
echo ""

echo -e "${BLUE}8. MONITOR GPU UTILIZATION${NC}"
echo "   Monitor GPU during batch processing"
echo ""
echo "   watch -n 1 nvidia-smi"
echo ""
echo "   Expected: GPU utilization 80-95% under load"
echo ""
echo "================================================================================"
echo ""

echo -e "${BLUE}9. INSTALL DEPENDENCIES${NC}"
echo "   Install required packages"
echo ""
echo "   pip install flask requests"
echo ""
echo "================================================================================"
echo ""

echo -e "${YELLOW}QUICK TEST WORKFLOW${NC}"
echo ""
echo "   # Terminal 1: Start server"
echo "   python3 $BASE_DIR/scripts/server/query_interface.py"
echo ""
echo "   # Terminal 2: Verify implementation"
echo "   python3 $BASE_DIR/scripts/tests/verify_batch_implementation.py"
echo ""
echo "   # Terminal 2: Run functional tests"
echo "   python3 $BASE_DIR/scripts/tests/test_batch_processing.py"
echo ""
echo "   # Terminal 2: Run benchmark"
echo "   python3 $BASE_DIR/scripts/tests/benchmark_batch_qps.py"
echo ""
echo "================================================================================"
echo ""

echo -e "${GREEN}For more information, see:${NC}"
echo "   - scripts/docs/BATCH_QUICK_START.md (quick start guide)"
echo "   - scripts/docs/BATCH_PROCESSING.md (complete documentation)"
echo "   - scripts/tests/README.md (test documentation)"
echo "   - scripts/BATCH_PROCESSING_IMPLEMENTATION_REPORT.md (implementation report)"
echo ""
echo "================================================================================"
