```mermaid
graph TD
    Genre[Genre]
    
    Genre --> Action["media:Action"]
    Genre --> Drama["media:Drama"]
    Genre --> Comedy["media:Comedy"]
    Genre --> SciFi["Science<br/>Fiction"]
    Genre --> Horror["media:Horror"]
    Genre --> Romance["media:Romance"]
    Genre --> Documentary["media:Documentary"]
    Genre --> Thriller["media:Thriller"]
```